env:
  es2021: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:fp/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
  - fp
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutating-methods:
    - error
    - allowedObjects:
      - "_"